var BuyerPaymentMethodCodeType =
{
	AM_EX: 'AmEx',
	CASH_IN_PERSON: 'CashInPerson',
	CASH_ON_PICKUP: 'CashOnPickup',
	CCACCEPTED: 'CCAccepted',
	COD: 'COD',
	CODPRE_PAY_DELIVERY: 'CODPrePayDelivery',
	CREDIT_CARD: 'CreditCard',
	CUSTOM_CODE: 'CustomCode',
	DINERS: 'Diners',
	DIRECT_DEBIT: 'DirectDebit',
	DISCOVER: 'Discover',
	ELV: 'ELV',
	ESCROW: 'Escrow',
	INTEGRATED_MERCHANT_CREDIT_CARD: 'IntegratedMerchantCreditCard',
	LOAN_CHECK: 'LoanCheck',
	MOCC: 'MOCC',
	MONEYBOOKERS: 'Moneybookers',
	MONEY_XFER_ACCEPTED: 'MoneyXferAccepted',
	MONEY_XFER_ACCEPTED_IN_CHECKOUT: 'MoneyXferAcceptedInCheckout',
	NONE: 'None',
	OTHER: 'Other',
	OTHER_ONLINE_PAYMENTS: 'OtherOnlinePayments',
	PAISA_PAY_ACCEPTED: 'PaisaPayAccepted',
	PAISA_PAY_ESCROW: 'PaisaPayEscrow',
	PAISA_PAY_ESCROW_EMI: 'PaisaPayEscrowEMI',
	PAYMATE: 'Paymate',
	PAYMENT_SEE_DESCRIPTION: 'PaymentSeeDescription',
	PAY_ON_PICKUP: 'PayOnPickup',
	PAY_PAL: 'PayPal',
	PAY_PAL_CREDIT: 'PayPalCredit',
	PAY_UPON_INVOICE: 'PayUponInvoice',
	PERSONAL_CHECK: 'PersonalCheck',
	POSTAL_TRANSFER: 'PostalTransfer',
	PRE_PAY_DELIVERY: 'PrePayDelivery',
	PRO_PAY: 'ProPay',
	QIWI: 'QIWI',
	STANDARD_PAYMENT: 'StandardPayment',
	VISA_MC: 'VisaMC'
};
module.exports = BuyerPaymentMethodCodeType;