var SellingManagerEmailTypeCodeType =
{
	CUSTOM_CODE: 'CustomCode',
	CUSTOM_EMAIL_TEMPLATE10: 'CustomEmailTemplate10',
	CUSTOM_EMAIL_TEMPLATE11: 'CustomEmailTemplate11',
	CUSTOM_EMAIL_TEMPLATE12: 'CustomEmailTemplate12',
	CUSTOM_EMAIL_TEMPLATE13: 'CustomEmailTemplate13',
	CUSTOM_EMAIL_TEMPLATE14: 'CustomEmailTemplate14',
	CUSTOM_EMAIL_TEMPLATE15: 'CustomEmailTemplate15',
	CUSTOM_EMAIL_TEMPLATE16: 'CustomEmailTemplate16',
	CUSTOM_EMAIL_TEMPLATE17: 'CustomEmailTemplate17',
	CUSTOM_EMAIL_TEMPLATE18: 'CustomEmailTemplate18',
	CUSTOM_EMAIL_TEMPLATE19: 'CustomEmailTemplate19',
	CUSTOM_EMAIL_TEMPLATE1: 'CustomEmailTemplate1',
	CUSTOM_EMAIL_TEMPLATE20: 'CustomEmailTemplate20',
	CUSTOM_EMAIL_TEMPLATE2: 'CustomEmailTemplate2',
	CUSTOM_EMAIL_TEMPLATE3: 'CustomEmailTemplate3',
	CUSTOM_EMAIL_TEMPLATE4: 'CustomEmailTemplate4',
	CUSTOM_EMAIL_TEMPLATE5: 'CustomEmailTemplate5',
	CUSTOM_EMAIL_TEMPLATE6: 'CustomEmailTemplate6',
	CUSTOM_EMAIL_TEMPLATE7: 'CustomEmailTemplate7',
	CUSTOM_EMAIL_TEMPLATE8: 'CustomEmailTemplate8',
	CUSTOM_EMAIL_TEMPLATE9: 'CustomEmailTemplate9',
	FEEDBACK_REMINDER_EMAIL: 'FeedbackReminderEmail',
	INVOICE_NOTIFICATION: 'InvoiceNotification',
	MANUAL_ENTRY: 'ManualEntry',
	PAYMENT_RECEIVED_EMAIL: 'PaymentReceivedEmail',
	PAYMENT_REMINDER_EMAIL: 'PaymentReminderEmail',
	PERSONALIZED_EMAIL: 'PersonalizedEmail',
	REQUEST_FOR_SHIPPING_ADDRESS_EMAIL: 'RequestForShippingAddressEmail',
	SHIPMENT_SENT_EMAIL: 'ShipmentSentEmail',
	WINNING_BUYER_EMAIL: 'WinningBuyerEmail'
};
module.exports = SellingManagerEmailTypeCodeType;