var ShippingPackageCodeType =
{
	BULKY_GOODS: 'BulkyGoods',
	CARAVAN: 'Caravan',
	CARS: 'Cars',
	CUSTOM_CODE: 'CustomCode',
	EUROPALLET: 'Europallet',
	EXPANDABLE_TOUGH_BAGS: 'ExpandableToughBags',
	EXTRA_LARGE_PACK: 'ExtraLargePack',
	FURNITURE: 'Furniture',
	INDUSTRY_VEHICLES: 'IndustryVehicles',
	LARGE_CANADA_POST_BOX: 'LargeCanadaPostBox',
	LARGE_CANADA_POST_BUBBLE_MAILER: 'LargeCanadaPostBubbleMailer',
	LARGE_ENVELOPE: 'LargeEnvelope',
	LETTER: 'Letter',
	MAILING_BOXES: 'MailingBoxes',
	MEDIUM_CANADA_POST_BOX: 'MediumCanadaPostBox',
	MEDIUM_CANADA_POST_BUBBLE_MAILER: 'MediumCanadaPostBubbleMailer',
	MOTORBIKES: 'Motorbikes',
	NONE: 'None',
	ONE_WAY_PALLET: 'OneWayPallet',
	PACKAGE_THICK_ENVELOPE: 'PackageThickEnvelope',
	PADDED_BAGS: 'PaddedBags',
	PARCEL_OR_PADDED_ENVELOPE: 'ParcelOrPaddedEnvelope',
	ROLL: 'Roll',
	SMALL_CANADA_POST_BOX: 'SmallCanadaPostBox',
	SMALL_CANADA_POST_BUBBLE_MAILER: 'SmallCanadaPostBubbleMailer',
	TOUGH_BAGS: 'ToughBags',
	UPSLETTER: 'UPSLetter',
	USPSFLAT_RATE_ENVELOPE: 'USPSFlatRateEnvelope',
	USPSLARGE_PACK: 'USPSLargePack',
	VERY_LARGE_PACK: 'VeryLargePack',
	WINEPAK: 'Winepak'
};
module.exports = ShippingPackageCodeType;