var SiteCodeType =
{
	AUSTRALIA: 'Australia',
	AUSTRIA: 'Austria',
	BELGIUM_DUTCH: 'Belgium_Dutch',
	BELGIUM_FRENCH: 'Belgium_French',
	CANADA: 'Canada',
	CANADA_FRENCH: 'CanadaFrench',
	CHINA: 'China',
	CUSTOM_CODE: 'CustomCode',
	E_BAY_MOTORS: 'eBayMotors',
	FRANCE: 'France',
	GERMANY: 'Germany',
	HONG_KONG: 'HongKong',
	INDIA: 'India',
	IRELAND: 'Ireland',
	ITALY: 'Italy',
	MALAYSIA: 'Malaysia',
	NETHERLANDS: 'Netherlands',
	PHILIPPINES: 'Philippines',
	POLAND: 'Poland',
	RUSSIA: 'Russia',
	SINGAPORE: 'Singapore',
	SPAIN: 'Spain',
	SWEDEN: 'Sweden',
	SWITZERLAND: 'Switzerland',
	TAIWAN: 'Taiwan',
	UK: 'UK',
	US: 'US'
};
module.exports = SiteCodeType;