var SummaryFrequencyCodeType =
{
	CUSTOM_CODE: 'CustomCode',
	EVERY31DAYS: 'Every31Days',
	EVERY60DAYS: 'Every60Days',
	EVERY_FRIDAY: 'EveryFriday',
	EVERY_MONDAY: 'EveryMonday',
	EVERY_SATURDAY: 'EverySaturday',
	EVERY_SUNDAY: 'EverySunday',
	EVERY_THURSDAY: 'EveryThursday',
	EVERY_TUESDAY: 'EveryTuesday',
	EVERY_WEDNESDAY: 'EveryWednesday',
	MONTHLY_ON10TH: 'MonthlyOn10th',
	MONTHLY_ON11TH: 'MonthlyOn11th',
	MONTHLY_ON12TH: 'MonthlyOn12th',
	MONTHLY_ON13TH: 'MonthlyOn13th',
	MONTHLY_ON14TH: 'MonthlyOn14th',
	MONTHLY_ON15TH: 'MonthlyOn15th',
	MONTHLY_ON16TH: 'MonthlyOn16th',
	MONTHLY_ON17TH: 'MonthlyOn17th',
	MONTHLY_ON18TH: 'MonthlyOn18th',
	MONTHLY_ON19TH: 'MonthlyOn19th',
	MONTHLY_ON1ST: 'MonthlyOn1st',
	MONTHLY_ON20TH: 'MonthlyOn20th',
	MONTHLY_ON21ST: 'MonthlyOn21st',
	MONTHLY_ON22ND: 'MonthlyOn22nd',
	MONTHLY_ON23RD: 'MonthlyOn23rd',
	MONTHLY_ON24TH: 'MonthlyOn24th',
	MONTHLY_ON25TH: 'MonthlyOn25th',
	MONTHLY_ON26TH: 'MonthlyOn26th',
	MONTHLY_ON27TH: 'MonthlyOn27th',
	MONTHLY_ON28TH: 'MonthlyOn28th',
	MONTHLY_ON29TH: 'MonthlyOn29th',
	MONTHLY_ON2ND: 'MonthlyOn2nd',
	MONTHLY_ON30TH: 'MonthlyOn30th',
	MONTHLY_ON31ST: 'MonthlyOn31st',
	MONTHLY_ON3RD: 'MonthlyOn3rd',
	MONTHLY_ON4TH: 'MonthlyOn4th',
	MONTHLY_ON5TH: 'MonthlyOn5th',
	MONTHLY_ON6TH: 'MonthlyOn6th',
	MONTHLY_ON7TH: 'MonthlyOn7th',
	MONTHLY_ON8TH: 'MonthlyOn8th',
	MONTHLY_ON9TH: 'MonthlyOn9th'
};
module.exports = SummaryFrequencyCodeType;